export const actionIds = {
    "GetParticipantPositions": "GetParticipantPositions",
    "CreateApprovalRequest": "CreateApprovalRequest",
    "UpdateParticipantStatus": "UpdateParticipantStatus",
    "SyncHubParticipantsToPortal": "SyncHubParticipantsToPortal",
    "GetSettlementId": "GetSettlementId",
    "GetGreeting": "GetGreeting",
    "GetContactList": "GetContactList",
    "CreateNewAnnouncement": "CreateNewAnnouncement",
    "GetParticipantList": "GetParticipantList",
    "ChangeCurrentPassword": "ChangeCurrentPassword",
    "CreateNewParticipantUser": "CreateNewParticipantUser",
    "GetParticipantUserList": "GetParticipantUserList",
    "CreateUser": "CreateUser",
    "ModifyUser": "ModifyUser",
    "ModifyUserStatus": "ModifyUserStatus",
    "GetUserProfile": "GetUserProfile",
    "GetExistingUser": "GetExistingUser",
    "ResetCurrentPassword": "ResetCurrentPassword",
    "ModifyApprovalAction": "ModifyApprovalAction",
    "GetPendingApprovalList": "GetPendingApprovalList",
    "GetLiquidityProfileList": "GetLiquidityProfileList",
    "CreateLiquidityProfile": "CreateLiquidityProfile",
    "RemoveLiquidityProfile": "RemoveLiquidityProfile",
    "ModifyLiquidityProfile": "ModifyLiquidityProfile",
    "ModifyContact": "ModifyContact",
    "GetParticipantProfile": "GetParticipantProfile",
    "RemoveContact": "RemoveContact",
    "ModifyParticipantProfile": "ModifyParticipantProfile",
    "GetAuditByParticipantList": "GetAuditByParticipantList",
    "GetAuditList": "GetAuditList",
    "GetTransferStateList": "GetTransferStateList",
    "GetTransferDetail": "GetTransferDetail",
    "GetTransferList": "GetTransferList"
} as const;

export type ActionId = keyof typeof actionIds;