// SPDX-License-Identifier: Apache-2.0
// Copyright 2024-2026 ThitsaWorks Pte. Ltd.
export const menuIds : Record<string, number>= {
    'home': 2,
    'participants': 3,
    'participant_positions': 4,
    'participant': 5,
    'user_management': 6,
    'users': 7,
    'transfers': 8,
    'settlement': 9,
    'settlement_models': 10,
    'settlement_windows': 11,
    'finalize_settlement': 12,
    'reports': 13,
    'settlement_bank_report': 14,
    'settlement_detail_report': 15,
    'settlement_summary_report': 16,
    'settlement_statement_report': 17,
    'settlement_audit_report': 18,
    'audit_report': 19,
    'pending_approvals': 20,
    'audit': 21,
    'support_center': 22,
    'transaction_detail_report': 23,
    'management_summary_report': 24,
    'dfsp_settlement_overview_report': 25,
    'settlement_bank_report_usecase': 26,
    'transfer_settlement_report': 27,
    'system_admin': 28,
    'fee_settlement_report': 29,
    'fee_settlement_summary_report': 30,
    'fee_summary_report': 31,
    'role_permission': 32,
    'ndc_alert_settings': 33,
    'notification_delivery_log': 34,
    'pacs_029_transaction_settlement_report': 35,
    'pacs_029_fee_settlement_report': 36
}
