[Interface]
Address = 10.252.1.19/32
PrivateKey = 8IUG/reJ3JAEIqjcg+1jX3k74KFETNy1avaCEAgioko=
DNS = 1.1.1.1

[Peer]
PublicKey = 6cCHIL3zmIpmWy+GacMAkGHoOd5vHvd/y1WoJHiAI1Y=
PresharedKey = B8hCNAnYHbmB4yRthKp4MRD358nCoJ6rLsDwtquWSQ4=
AllowedIPs = 10.25.0.0/16
Endpoint = 18.141.90.224:51820
PersistentKeepalive = 15
