[Interface]
Address = 10.252.1.19/32
PrivateKey = 2POkt3c5ApCzODdjfcZOxfqGtU6fZ3S2PZt4qJdwL28=
DNS = 1.1.1.1

[Peer]
PublicKey = RoG3vcKe04iECQ+JQB/kSnGcYHR5JsOUUmQijj37Yyk=
PresharedKey = 22Tb4N8aFK5BilI4DW0+7np1WQRrikFPYBEXM+uqnLc=
AllowedIPs = 10.25.0.0/16
Endpoint = 54.169.119.25:51820
PersistentKeepalive = 15
